version: '3'
services:
  umb_back:
    container_name: 'umb_back'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '/umb_backend/node_modules'
    ports:
      - "4008:4008"

